// Code generated by "stringer -type=Op"; DO NOT EDIT.

package feeder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownOp-0]
	_ = x[Add-1]
	_ = x[Delete-2]
}

const _Op_name = "UnknownOpAddDelete"

var _Op_index = [...]uint8{0, 9, 12, 18}

func (i Op) String() string {
	idx := int(i) - 0
	if idx >= len(_Op_index)-1 {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[idx]:_Op_index[idx+1]]
}
